# Dockerfile-db
FROM mysql:8.0

# Open Port
EXPOSE 3306

# Configure Environment Variable
#ENV HOSTNAME="sysadmin-db"
#ENV MYSQL_ROOT_PASSWORD=root
#ENV MYSQL_ROOT_PASSWORD="sysadmin-db-rootpw"
#ENV MYSQL_USER=ipums
#ENV MYSQL_PASSWORD=sysadmin-exercise
#ENV MYSQL_DATABASE="ipums"

# Setup database scheme
ADD schema.sql /docker-entrypoint-initdb.d/schema.sql
ADD auth.sql /docker-entrypoint-initdb.d/auth.sql
