# Dockerfile-web
FROM phusion/passenger-customizable

# Set correct environment variables.
ENV HOME /root

# Use baseimage-docker's init process.
CMD ["/sbin/my_init"]

# Expose Nginx HTTP service
EXPOSE 80

# Install python flask support
RUN /pd_build/utilities.sh       \
    /pd_build/python.sh          \
 && apt-get install -y           \ 
     default-libmysqlclient-dev  \  
     python-pip                  \  
 &&  pip install flask           \
     flask-mysqldb

# Start Nginx / Passenger
RUN rm -f /etc/service/nginx/down

# Remove the default site
RUN rm /etc/nginx/sites-enabled/default
ADD ./webapp.conf /etc/nginx/sites-enabled/webapp.conf

# Adding Web Application
ADD ./app.py /home/app/webapp/app.py
ADD ./config.py /home/app/webapp/config.py
ADD ./passenger_wsgi.py /home/app/webapp/passenger_wsgi.py
RUN chown -R app:app /home/app/webapp

